### ISSUE TITLE
Delay of file update in Github API

### ISSUE THREAD

**Issue by NinaWie** [jannisborn/PennyMe#251]
There is a delay between commits and their realization in the github api. In our workflow, this leads to problems if two changes are done shortly after another (e.g., a new machine is proposed and two minutes later an old machine is edited). An outdated version of the server_locations file is downloaded in this case and overwrites previous changes. 
I tested it by repeatedly downloading the server locations with the `load_latest_json` method:
```
file_url = "https://api.github.com/repos/jannisborn/PennyMe/contents//data/server_locations.json?ref=machine_updates"
from pennyme.github_update import HEADERS, load_latest_json
while True:
    server_locations, sha = load_latest_json()
    print(time.time(), server_locations["features"][-1])
    time.sleep(3)
```
It takes around 4 minutes after a commit until the updated file is used.

**Comment by jannisborn** [comment]
Discussed 2 potential solutions:
- retrieve the file directly from github.com instead of via the API (since the repo is public)
- Detect the last push event on the entire repo (or the last commit on the branch). Potentially this is updated faster than the file itself

**Comment by jannisborn** [comment]
First solution doesnt work, will go for second one.

Incoming machine edits should be handled with a Queue. NewMachineRequests, submitted to a separate flask endpoint, should be fed to the same queue. The queue handler should essentially ensure the above. Basically, when running a job in the queue, we first detect the last push event (and wait up to 5 minutes if it was more recent), then we start the execution. We also need a scheduler to avoid the queue from running during the cron job execution for the location-differ
Ideally, that script would just be another job, fed to the same Queue but I'm unsure how easy this is to realize.

In any way, all of this means that we have an upper-bound of processing one edit per 5 minutes. Let's cross fingers we never reach high traffic conditions that force us to reconsider
