### ISSUE TITLE
Toggle button for hiding the retired machines

### ISSUE THREAD

**Issue by NinaWie** [jannisborn/PennyMe#55]
We decided to add a button to hide retired machines, instead of fully deleting machines. When users mark a "retired" machines as "visited", they will see it in any case, but if it's retired and they haven't visited it, they should have the option to not show them.

**Comment by jannisborn** [comment]
I hade another thought to slightly rework this issue

Together with #58, this issue will control which pins are shown on the map. A toggle for hiding retired machines is nice, but similarly, there should be toggles to show:
- visited machines
- marked machines
- unvisited machines

If we make four independent toggles, plus we solve #58, the user has perfect controllability over the pins being shown. The default can be that visisted, marked and unvisited are shown whereas retired is not shown
