### ISSUE TITLE
check OSM machines

### ISSUE THREAD

**Issue by NinaWie** [jannisborn/PennyMe#84]
We should try to get the penny machines that are tagged on OSM (tag: elongated coins, category: verkaufsstelle) and compare the coordinates to our database.

**Comment by UserMicha** [comment]
Here comes the data, generated with following Overpass API request: 
_node
[vending=elongated_coin]
({{bbox}});
out;_
on https://overpass-turbo.eu.  Should cover the whole world (map zoomed out). 


[OSM-Overpass-export-World.zip](https://github.com/jannisborn/PennyMe/files/13166404/OSM-Overpass-export-World.zip)

**Comment by jannisborn** [comment]
Wunderbar, vielen Dank! Wir schauen beizeiten mal in die Datei und versuchen die einträge zu denen in unserer Datenbank zu matchen. Hab da ein paar Ideen mit der Places API von google maps, aber ganz trivial ist das nicht!

Auf jeden Fall ein super Weg die DB zu erweitern

**Comment by jannisborn** [comment]
@UserMicha habe einen Weg gefunden diese gezippte geojson datei automatisch via Python abzufragen:

```py
import overpy

# Create an Overpass API instance
api = overpy.Overpass()

# Define the bounding box coordinates
bbox = (-90, -180, 90, 180)  # Example: Paris, France

# Define the Overpass QL query
query = f"""
node
  ["vending"="elongated_coin"]
  (-90, -180, 90, 180);
out;
"""

# Send the query to the Overpass API and get the response
result = api.query(query)

# The 'result' variable now contains the data returned by the Overpass API
len(result.nodes)
```

Das spuckt dann 808 einträge aus, in deiner Datei waren 805, scheint also quasi das gleiche zu sein. Somit können wir auch hier jeden Tag eine Abfrage starten und die Ergebnisse dann integrieren

**Comment by UserMicha** [comment]
Super, eine elegante Lösung! Bravo!! Der Unterschied sind bestimmt zwischenzeitlich neu eingetragene Maschinen. Kann gut sein, dass zwei von mir dazu gekommen sind :-)
